services:
  web:
    build: .
    restart: always
    # depends_on:
    #   - db
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
#   db:
#     image: postgres:15
#     restart: always
#     env_file: .env
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
# volumes:
#   postgres_data:
