# Generated by Django 3.2.25 on 2025-01-30 18:29
import logging
import environ
from django.db import migrations

logger = logging.getLogger(__name__)

def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    env = environ.Env()
    USERNAME = env.str("ADMIN_USERNAME")
    PASSWORD = env.str("ADMIN_PASSWORD")
    EMAIL = env.str("ADMIN_EMAIL")

    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        logger.info("Creating new superuser")
        admin = user.objects.create_superuser(
           username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()
    else:
        logger.info("Superuser already created!")
class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_published_in'),
    ]
    operations = [migrations.RunPython(generate_superuser)]
