# Generated by Django 5.1.5 on 2025-02-13 18:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20250130_1829'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryEval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateFinished', models.DateField()),
                ('dateStarted', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UR', 'Unread'), ('IP', 'In Progress'), ('R', 'Read')], default='UR', max_length=2)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='stories.reader')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='stories.story')),
            ],
            options={
                'unique_together': {('story', 'reader')},
            },
        ),
    ]
